name = "licenseuri"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-07-01"

[build]
upload.format = "service-worker"
upload.main = "./dist/worker.js"
command = "npm run build"
