name: CI & Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run build
      - name: Build project
        run: npm run build

      # OPTIONAL: Run tests or lint here
      # - name: Run tests
      #   run: npm test

      # Deploy to Cloudflare Workers
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
